name: "Find environment"
description: "Provides environment information according to Jauntin's conventions. Workflow dispatches are for prod, and dev/dev-adhoc* or master/uat-adhoc* are for dev and uat"
inputs:
  event-name:
    description: "Provide github.event_name"
    required: true
  ref:
    description: "Provide github.ref"
    required: true
outputs:
  cluster:
    description: "Name of the cluster to be used"
    value: ${{ steps.env.outputs.cluster }}
  env:
    description: "Name of the environment"
    value: ${{ steps.env.outputs.env }}
  env-long:
    description: "Long name of the environment, e.g. production"
    value: ${{ steps.env.outputs.env-long }}
runs:
  using: "composite"
  steps:
    - id: env
      shell: bash
      run: |
        if [[ "${{ inputs.event-name }}" == "workflow_dispatch" ]]; then
          export DEPLOY_ENV="prod"
        elif [[ "${{ inputs.ref }}" == master || "${{ inputs.ref }}" == uat* ]]; then
          export DEPLOY_ENV="uat"
        else
          export DEPLOY_ENV="dev"
        fi
        echo "::set-output name=env::$DEPLOY_ENV"
        if [[ "$DEPLOY_ENV" == "prod" ]]; then
          echo "::set-output name=env-long::production"
          echo "::set-output name=cluster::Prod"
        else
          echo "::set-output name=env-long::$DEPLOY_ENV"
          echo "::set-output name=cluster::Dev"
        fi
