name: 'Project maintenance automation'
description: 'Automatically move issues to the next iteration.'
branding:
  icon: 'calendar'
  color: 'blue'
inputs:
  owner:
    description: The account name of the GitHub organization.
    default: jauntin
    required: true
  number:
    description: Project number as you see it in the URL of the project.
    default: '4'
    required: true
  token:
    description: Personal access token or an OAuth token. the write:org scope is required for read-write access.
    required: true
  iterationFieldName:
    description: The name of your iteration field.
    default: Iteration
    required: true
  statusFieldName:
    description: Usually 'Status'
    default: 'Status'
    required: true
  doneStatusName:
    description: Status of the issues to move to the current iteration.
    default: "✅ Done"
    required: true
  daysToKeepOnDone:
    description: The number of days to keep items in the done column without any updates
    default: '50'
    required: true
runs:
  using: 'node20'
  main: 'dist/index.js'
