name: "Build and Push Container"
description: "Builds a container and pushes it to the github container repository"
inputs:
  tag:
    required: true
    description: "build hash or other identifier"
  location:
    required: true
    description: "e.g. jauntin/obi-phpfpm-app"
  username:
    required: true
    description: "Container repository username"
  password:
    required: true
    description: "Container repository password"
outputs: {}
runs:
  using: "composite"
  steps:
    - uses: docker/setup-buildx-action@v1
    - uses: actions/cache@v2
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ inputs.tag }}
        restore-keys: |
          ${{ runner.os }}-buildx-
    - uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ inputs.username }}
        password: ${{ inputs.password }}
    - uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ghcr.io/${{ inputs.location }}:${{ inputs.tag }}
        cache-from: type=local,src=/tmp/.buildx-cache
        cache-to: type=local,dest=/tmp/.buildx-cache-new
    - shell: bash
      run: |
        rm -rf /tmp/.buildx-cache
        mv /tmp/.buildx-cache-new /tmp/.buildx-cache
