name: Delete Old Images

description: >
  Delete old GHCR Images by date

author: Jauntin

branding:
  icon: delete
  color: blue

inputs:
  token:
    description: >
      Token with the necessary scopes to delete package versions.
    required: true
  owner:
    description: >
      Owner of the package (user or organization)
    required: true
  name:
    description: >
      Name of the package containing the images to delete
    required: true
  seconds:
    description: >
      Number of seconds to preserve. E.g. 3600 means we delete images older than one hour
    required: true
    default: "3600"
runs:
  using: "node12"
  main: "dist/index.js"
